# Generated by Django 5.0.2 on 2024-02-24 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_name', models.CharField(max_length=126)),
                ('to_address', models.CharField(max_length=126)),
                ('to_pin', models.IntegerField()),
                ('to_gst', models.CharField(max_length=126)),
            ],
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_name', models.CharField(max_length=126)),
                ('from_address', models.CharField(max_length=126)),
                ('from_pin', models.IntegerField()),
                ('from_gst', models.CharField(max_length=126)),
            ],
        ),
    ]
