# Generated by Django 5.0.2 on 2024-02-25 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0002_productform'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductForm',
        ),
    ]
